services:
  actual-server:
    image: actualbudget/actual-server:latest
    container_name: actual-server
    restart: unless-stopped
    ports:
      - '5006:5006'
    volumes:
      - /mnt/actual-data:/data
    networks:
      - caddy_net

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - DOMAIN=${VAULTWARDEN_DOMAIN}
      - SIGNUPS_ALLOWED=false
      - TZ=${TZ}
    volumes:
      - ${ROOT_DIR}/vaultwarden/data:/data
    ports:
      - 8080:80
    restart: unless-stopped
    networks:
      - caddy_net

  vikunja:
    image: vikunja/vikunja:latest
    container_name: vikunja
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VIKUNJA_SERVICE_PUBLICURL=${VIKUNJA_URL}
      - TZ=${TZ}
      - VIKUNJA_OUTGOINGREQUESTS_ALLOWNONROUTABLEIPS=true
    ports:
      - 3456:3456
    volumes:
      - ${ROOT_DIR}/vikunja/files:/app/vikunja/files
      - ${ROOT_DIR}/vikunja/db:/db
    restart: unless-stopped
    networks:
      - caddy_net

  notifications:
    build: ./notifications
    container_name: notifications
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - VIKUNJA_URL=${VIKUNJA_URL}
      - MEALIE_URL=${MEALIE_URL}
    ports:
      - 8001:8001
    restart: unless-stopped
    networks:
      - caddy_net
      
  omni-tools:
    image: iib0011/omni-tools:latest
    container_name: omni-tools
    restart: unless-stopped
    ports:
      - 8085:80
    networks:
      - caddy_net
      
  bentopdf:
    image: bentopdf/bentopdf:latest
    container_name: bentopdf
    restart: unless-stopped
    ports:
      - 8086:8080
    networks:
      - caddy_net

  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT_DIR}/freshrss/config:/config
    ports:
      - 8087:80
    restart: unless-stopped
    networks:
      - caddy_net

  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MEALIE_URL=${MEALIE_URL}
      - HTTP_ALLOW_LIST=notifications
    volumes:
      - ${ROOT_DIR}/mealie/data:/app/data/
    ports:
      - 9925:9000 # Maps Mealie's internal port 9000 to 9925 on your host
    restart: unless-stopped
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
